DROP TABLE IF EXISTS public.raw_core CASCADE;

CREATE TABLE public.raw_core (
    age INTEGER,
    aweekend INTEGER,
    died INTEGER,
    discwt character varying(20) COLLATE pg_catalog. "default",
    dispuniform INTEGER,
    dmonth INTEGER,
    dqtr INTEGER,
    drg character varying(20) COLLATE pg_catalog. "default",
    drgver character varying(20) COLLATE pg_catalog. "default",
    drg_nopoa character varying(20) COLLATE pg_catalog. "default",
    i10_dx1 character varying(20) COLLATE pg_catalog. "default",
    i10_dx2 character varying(20) COLLATE pg_catalog. "default",
    i10_dx3 character varying(20) COLLATE pg_catalog. "default",
    i10_dx4 character varying(20) COLLATE pg_catalog. "default",
    i10_dx5 character varying(20) COLLATE pg_catalog. "default",
    i10_dx6 character varying(20) COLLATE pg_catalog. "default",
    i10_dx7 character varying(20) COLLATE pg_catalog. "default",
    i10_dx8 character varying(20) COLLATE pg_catalog. "default",
    i10_dx9 character varying(20) COLLATE pg_catalog. "default",
    i10_dx10 character varying(20) COLLATE pg_catalog. "default",
    i10_dx11 character varying(20) COLLATE pg_catalog. "default",
    i10_dx12 character varying(20) COLLATE pg_catalog. "default",
    i10_dx13 character varying(20) COLLATE pg_catalog. "default",
    i10_dx14 character varying(20) COLLATE pg_catalog. "default",
    i10_dx15 character varying(20) COLLATE pg_catalog. "default",
    i10_dx16 character varying(20) COLLATE pg_catalog. "default",
    i10_dx17 character varying(20) COLLATE pg_catalog. "default",
    i10_dx18 character varying(20) COLLATE pg_catalog. "default",
    i10_dx19 character varying(20) COLLATE pg_catalog. "default",
    i10_dx20 character varying(20) COLLATE pg_catalog. "default",
    i10_dx21 character varying(20) COLLATE pg_catalog. "default",
    i10_dx22 character varying(20) COLLATE pg_catalog. "default",
    i10_dx23 character varying(20) COLLATE pg_catalog. "default",
    i10_dx24 character varying(20) COLLATE pg_catalog. "default",
    i10_dx25 character varying(20) COLLATE pg_catalog. "default",
    i10_dx26 character varying(20) COLLATE pg_catalog. "default",
    i10_dx27 character varying(20) COLLATE pg_catalog. "default",
    i10_dx28 character varying(20) COLLATE pg_catalog. "default",
    i10_dx29 character varying(20) COLLATE pg_catalog. "default",
    i10_dx30 character varying(20) COLLATE pg_catalog. "default",
    i10_dx31 character varying(20) COLLATE pg_catalog. "default",
    i10_dx32 character varying(20) COLLATE pg_catalog. "default",
    i10_dx33 character varying(20) COLLATE pg_catalog. "default",
    i10_dx34 character varying(20) COLLATE pg_catalog. "default",
    i10_dx35 character varying(20) COLLATE pg_catalog. "default",
    i10_ecause1 character varying(20) COLLATE pg_catalog. "default",
    i10_ecause2 character varying(20) COLLATE pg_catalog. "default",
    i10_ecause3 character varying(20) COLLATE pg_catalog. "default",
    i10_ecause4 character varying(20) COLLATE pg_catalog. "default",
    elective INTEGER,
    female INTEGER,
    hcup_ed INTEGER,
    hosp_nrd BIGINT,
    key_nrd BIGINT,
    los INTEGER,
    mdc character varying(20) COLLATE pg_catalog. "default",
    mdc_nopoa character varying(20) COLLATE pg_catalog. "default",
    i10_ndx INTEGER,
    i10_necause INTEGER,
    i10_npr INTEGER,
    nrd_daystoevent INTEGER,
    nrd_stratum BIGINT,
    nrd_visitlink character varying(20) COLLATE pg_catalog. "default",
    pay1 INTEGER,
    pl_nchs INTEGER,
    i10_pr1 character varying(20) COLLATE pg_catalog. "default",
    i10_pr2 character varying(20) COLLATE pg_catalog. "default",
    i10_pr3 character varying(20) COLLATE pg_catalog. "default",
    i10_pr4 character varying(20) COLLATE pg_catalog. "default",
    i10_pr5 character varying(20) COLLATE pg_catalog. "default",
    i10_pr6 character varying(20) COLLATE pg_catalog. "default",
    i10_pr7 character varying(20) COLLATE pg_catalog. "default",
    i10_pr8 character varying(20) COLLATE pg_catalog. "default",
    i10_pr9 character varying(20) COLLATE pg_catalog. "default",
    i10_pr10 character varying(20) COLLATE pg_catalog. "default",
    i10_pr11 character varying(20) COLLATE pg_catalog. "default",
    i10_pr12 character varying(20) COLLATE pg_catalog. "default",
    i10_pr13 character varying(20) COLLATE pg_catalog. "default",
    i10_pr14 character varying(20) COLLATE pg_catalog. "default",
    i10_pr15 character varying(20) COLLATE pg_catalog. "default",
    prday1 INTEGER,
    prday2 INTEGER,
    prday3 INTEGER,
    prday4 INTEGER,
    prday5 INTEGER,
    prday6 INTEGER,
    prday7 INTEGER,
    prday8 INTEGER,
    prday9 INTEGER,
    prday10 INTEGER,
    prday11 INTEGER,
    prday12 INTEGER,
    prday13 INTEGER,
    prday14 INTEGER,
    prday15 INTEGER,
    rehabtransfer INTEGER,
    resident INTEGER,
    samedayevent INTEGER,
    totchg BIGINT,
    year INTEGER,
    zipinc_qrtl INTEGER,
    dxver character varying(20) COLLATE pg_catalog. "default",
    prver character varying(20) COLLATE pg_catalog. "default")
